// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "SmartLink_Project/domain"

	mock "github.com/stretchr/testify/mock"
)

// LayananData is an autogenerated mock type for the LayananData type
type LayananData struct {
	mock.Mock
}

// AddLayananData provides a mock function with given fields: newLayanan
func (_m *LayananData) AddLayananData(newLayanan domain.Layanan) domain.Layanan {
	ret := _m.Called(newLayanan)

	var r0 domain.Layanan
	if rf, ok := ret.Get(0).(func(domain.Layanan) domain.Layanan); ok {
		r0 = rf(newLayanan)
	} else {
		r0 = ret.Get(0).(domain.Layanan)
	}

	return r0
}

type mockConstructorTestingTNewLayananData interface {
	mock.TestingT
	Cleanup(func())
}

// NewLayananData creates a new instance of LayananData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLayananData(t mockConstructorTestingTNewLayananData) *LayananData {
	mock := &LayananData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
